# Generated by Django 4.2.7 on 2023-11-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Nunc eget augue eu diam finibus dapibus quis sit amet leo. Ut gravida facilisis velit mollis fringilla. Quisque efficitur elit'),
        ),
    ]
